[package]
name = "chisel"
version = "0.1.0"
edition = "2024"
authors     = ["Jonathan Wahrenberg <jonathan@wahrenberg.com>"]
license     = "Apache-2.0"
repository  = "https://github.com/yourname/chisel"

[dependencies]
